### ISSUE TITLE
Please put a license file

### ISSUE THREAD

**Issue by allada** [u1roh/kd-tree#14]
Can you please put a license on this project so we know what kind of use cases are allowed with/without attribution?

**Comment by u1roh** [comment]
This library is distrubuted under the MIT License, as shown in https://crates.io/crates/kd-tree .
![Screenshot from 2023-01-30 17-58-11](https://user-images.githubusercontent.com/1583937/215432114-724378d3-a19c-4009-8e54-e5a8e5eb02b9.png)

I have just put the lincense file at https://github.com/u1roh/kd-tree/blob/main/LICENSE .
