### ISSUE TITLE
NAlgebra support passing a matrix instead of separate points?

### ISSUE THREAD

**Issue by JulianKnodt** [u1roh/kd-tree#20]
Currently this KDTree supports passing point separately, is it possible instead to pass a matrix of points, where each column is a single point?

**Comment by u1roh** [comment]
@JulianKnodt It looks difficult.

You can do that for statically sized matrix such as `Matrix3<T>` (= `Matrix<T, U3, U3, ArrayStorage<T, 3, 3>>)`. The underlying data structure of such statically sized matrix is 2-dimensional array like `[[T; R]; C]`, and you can construct `KdSlice` for the array.

But this is not meaningful. You want it for dynamically sized matrix s.t. `DMatrix`.

Unfotunately, the underlying data structure of `DMatrix` is `VecStorage<T, R, C>` and it's not a 2-dimensional array.

I don't have any good solution.
