### ISSUE TITLE
impl for nalgebra vectors and points

### ISSUE THREAD

**Issue by maccesch** [u1roh/kd-tree#3]
It would be awesome to have `impl`s for the nalgebra types behind some feature flag maybe.

If you're interested I could make a PR.

**Comment by u1roh** [comment]
@maccesch  It sounds great. I will welcome your PR!

**Comment by u1roh** [comment]
I did it. (not published yet)

**Comment by maccesch** [comment]
Oh you're fast! Thanks!

**Comment by u1roh** [comment]
I published it!
Check the latest `kd-tree` crate. https://crates.io/crates/kd-tree
